var placetovisit = ["china", "america", "italy", "germany", "russia"];
console.log(placetovisit);
console.log(placetovisit.sort());
console.log(placetovisit);
console.log(placetovisit.sort().reverse());
console.log(placetovisit);
console.log(placetovisit.reverse());
console.log(placetovisit.reverse());
var sortedArray = ["china", "america", "italy", "germany", "russia"];
sortedArray.sort();
console.log(sortedArray);
sortedArray.reverse();
console.log(sortedArray);
